apiVersion: v1
kind: Secret
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "210"
  name: ibm-ban-secret
  namespace: cp4ba
type: Opaque
stringData:
  navigatorDBUsername: "icnadm"
  navigatorDBPassword: "Passw0rd"
  keystorePassword: "changeit"
  ltpaPassword: "passw0rd"
  appLoginUsername: "cpadmin"
  appLoginPassword: "Passw0rd"